name: Lighthouse CI

on:
  push:
    branches-ignore:
      - main

jobs:
  LighthouseCI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.13.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.0
          cache: "yarn"
          registry-url: "https://npm.pkg.github.com"

      - name: install deps
        run: yarn --frozen-lockfile

      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]sx?') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-

      - name: build
        run: yarn build

      - name: Lighthouse CI
        run: yarn lhci
